complexity cyclomaty added
solid-software/solid-metrics pull request #1
Opened 2023-07-19 14:23 UTC by tomboichik

2023-07-19 16:40 UTC, solid-vovabeloded requested changes
Good job, @tomboichik! I've added a couple of initial suggestions here - please, take a look.

2023-07-19 16:40 UTC, solid-vovabeloded commented on lib/complexity_metric.dart
> +class _ComplexityMetricLinter extends PluginBase {
```suggestion
class _CyclomaticComplexityLinter extends PluginBase {
```
Does it make sense?

2023-07-19 16:40 UTC, solid-vovabeloded commented on lib/visitor/complexity_metric_flow_visitor.dart
> +class ComplexityMetricFlowVisitor extends RecursiveAstVisitor<void> {
```suggestion
class CyclomaticComplexityVisitor extends RecursiveAstVisitor<void> {
```

2023-07-20 08:51 UTC, solid-vovabeloded requested changes
I've added a few more suggestions here. Also, please, create an example project in the `example` dir so we can test out lints there.

2023-07-20 08:51 UTC, solid-vovabeloded commented on lib/complexity_metric.dart
> +  static const _code = LintCode(
```suggestion
  static const _lintCode = LintCode(
```
Would it be a bit more clear?

2023-07-20 08:51 UTC, solid-vovabeloded commented on lib/complexity_metric.dart
> +  /// Constructor class
Please, add more meaningful documentation similar to the following one: 
```suggestion
  /// Creates a new instance of [ComplexityMetric].
```

2023-07-20 08:51 UTC, solid-vovabeloded commented on lib/complexity_metric.dart
> +class ComplexityMetric extends DartLintRule {
```suggestion
class CyclomaticComplexityMetric extends DartLintRule {
```

2023-07-20 08:51 UTC, solid-vovabeloded commented on lib/visitor/complexity_metric_flow_visitor.dart
> +    var token = firstToken;
```suggestion
    Token? token = firstToken;
```
I'd suggest using exact type in such cases since it is a bit more readable.

2023-07-20 09:03 UTC, tomboichik commented on lib/visitor/complexity_metric_flow_visitor.dart
> +class ComplexityMetricFlowVisitor extends RecursiveAstVisitor<void> {
Okay

2023-07-20 09:06 UTC, tomboichik commented on lib/complexity_metric.dart
> +  static const _code = LintCode(
I think yes

2023-07-20 10:47 UTC, solid-vovabeloded requested changes

2023-07-20 10:47 UTC, solid-vovabeloded commented on lib/cyclomatic_complexity_metric.dart
> +class CyclomaticComplexityMetric extends DartLintRule {
Does it make sense to extract this class into a separate file?

2023-07-20 10:47 UTC, solid-vovabeloded commented on example/pubspec.yaml
> +    path: ../../cyclomatic_complexity_metric
```suggestion
  cyclomatic_complexity_metric:
    path: ../
```

2023-07-20 10:47 UTC, solid-vovabeloded commented on lib/cyclomatic_complexity_metric.dart
> +    problemMessage: 'Check complexity',
Please, provide more meaningfull description for users.

2023-07-20 10:47 UTC, solid-vovabeloded commented on pubspec.yaml
> +name: cyclomatic_complexity_metric
```suggestion
name: solid_metrics
```

2023-07-20 11:18 UTC, solid-vovabeloded approved these changes
Just one suggestion and you're good to go.

2023-07-20 11:18 UTC, solid-vovabeloded commented on example/lib/example.dart
> +  if (true && true) {}
Let's make it fail for visibility.

2023-07-20 11:21 UTC, merged